/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashboardMedico;
import Controlador.HistorialCitasController;
import ConexionPostgreSQL.ConexionDB;
import Vista.InicioDeSesion;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JTextArea;


/**
 *
 * @author rober
 */
public class CitasAgendadas extends javax.swing.JFrame {

     private final HistorialCitasController controlador;
    
    public CitasAgendadas() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.controlador = new HistorialCitasController();
        configurarEventosJCalendar();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion2 = new javax.swing.JButton();
        btnDetallesCitas1 = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCalendarCitas1 = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCitasVisualizadas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(970, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion2.setText("Cerrar sesion");
        btnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 170, 30));

        btnDetallesCitas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDetallesCitas1.setText("Detalles de citas");
        btnDetallesCitas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesCitas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetallesCitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 170, 30));

        btnConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 170, 30));

        btnPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPacientes.setText("Citas agendadas");
        getContentPane().add(btnPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 170, 30));

        jPanel1.setBackground(new java.awt.Color(210, 242, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 880, 40));
        getContentPane().add(jCalendarCitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 880, 430));

        txtCitasVisualizadas.setColumns(20);
        txtCitasVisualizadas.setRows(5);
        jScrollPane1.setViewportView(txtCitasVisualizadas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 390, 250));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Blue and White Modern Medical Healthcare Presentation.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 566, 470, 220));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel5.setText("CITAS AGENDADAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cuenta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("MEDICAL CENTER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("VITALIS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DashboardMedicamentos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        ConsultaDiagnosticoReceta conDiagR = new ConsultaDiagnosticoReceta();
        conDiagR.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnDetallesCitas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesCitas1ActionPerformed
        // TODO add your handling code here:
        DetallesCitas detCitas = new DetallesCitas();
        detCitas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDetallesCitas1ActionPerformed

    private void btnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion2ActionPerformed
        // TODO add your handling code here:
        dispose();
        InicioDeSesion inSes = new InicioDeSesion();
        inSes.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesion2ActionPerformed


    
    // Configurar el evento del JCalendar
    private void configurarEventosJCalendar() {
        jCalendarCitas1.addPropertyChangeListener("calendar", evt -> {
            java.util.Date fechaSeleccionada = jCalendarCitas1.getDate();
            if (fechaSeleccionada != null) {
                cargarCitasPorFecha(new java.sql.Date(fechaSeleccionada.getTime()));
            }
        });
    }

  private void cargarCitasPorFecha(Date fecha) {
        try (Connection conn = ConexionDB.conectar()) {
            // Obtener citas desde el controlador
            ArrayList<String> citas = controlador.obtenerCitasPorFecha(fecha, conn);

            // Mostrar citas en el JTextArea
            txtCitasVisualizadas.setText(""); // Limpiar el cuadro de texto
            if (citas.isEmpty()) {
                txtCitasVisualizadas.setText("No hay citas programadas para esta fecha.");
            } else {
                for (String cita : citas) {
                    txtCitasVisualizadas.append(cita + "\n");
                }
            }
        } catch (Exception e) {
            System.err.println("Error al cargar citas: " + e.getMessage());
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitasAgendadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitasAgendadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitasAgendadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitasAgendadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitasAgendadas().setVisible(true);
            }
        });
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion2;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnDetallesCitas1;
    private javax.swing.JButton btnPacientes;
    private com.toedter.calendar.JCalendar jCalendarCitas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtCitasVisualizadas;
    // End of variables declaration//GEN-END:variables
}
