/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Controlador.UsuarioController;
import javax.swing.JOptionPane;


/**
 *
 * @author rober
 */
public class InicioDeSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioDeSesion
     */
    public InicioDeSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiedlCorreo = new javax.swing.JTextField();
        jContraseña = new javax.swing.JPasswordField();
        combxTipoUsuario = new javax.swing.JComboBox<>();
        btnEntrar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLabelCrearCuenta = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelCorreoEle = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jLabelVitalis = new javax.swing.JLabel();
        jLabelMedicalCenter = new javax.swing.JLabel();
        jLabeFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFiedlCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiedlCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFiedlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 390, 30));

        jContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 390, 30));

        combxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "MEDICO", "RECEPCIONISTA" }));
        getContentPane().add(combxTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 390, -1));

        btnEntrar.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 390, -1));

        btnRegistrarse.setBackground(new java.awt.Color(240, 224, 244));
        btnRegistrarse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(153, 102, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 390, 30));

        jLabelCrearCuenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCrearCuenta.setText("¿No tienes una cuenta?");
        getContentPane().add(jLabelCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabelTipoUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelTipoUsuario.setText("Tipo de usuario");
        getContentPane().add(jLabelTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 30));

        jLabelCorreoEle.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCorreoEle.setText("Correo electrónico");
        getContentPane().add(jLabelCorreoEle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelContraseña.setText("Contraseña");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 30));

        jLabelIniciarSesion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabelIniciarSesion.setText("INICIAR SESION");
        getContentPane().add(jLabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, 20));

        jLabelVitalis.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabelVitalis.setText("VITALIS");
        getContentPane().add(jLabelVitalis, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, 40));

        jLabelMedicalCenter.setFont(new java.awt.Font("Bookman Old Style", 1, 28)); // NOI18N
        jLabelMedicalCenter.setText("MEDICAL CENTER");
        getContentPane().add(jLabelMedicalCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, 40));

        jLabeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InicioSesion.jpg"))); // NOI18N
        getContentPane().add(jLabeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 960, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiedlCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiedlCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiedlCorreoActionPerformed

    private void jContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContraseñaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
String correo = txtFiedlCorreo.getText().trim();
String contraseña = new String(jContraseña.getPassword());
String tipoUsuario = combxTipoUsuario.getSelectedItem().toString();

if (correo.isEmpty() || contraseña.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, ingresa el correo electrónico y la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

UsuarioController usuarioController = new UsuarioController();
if (usuarioController.iniciarSesion(correo, contraseña, tipoUsuario)) {
    JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso. Bienvenido " + tipoUsuario.toLowerCase() + "!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    
    // Crear la ventana de Verificación
    Verificacion ventanaVerificacion = new Verificacion();
    ventanaVerificacion.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    ventanaVerificacion.setVisible(true);

    // Bloquear el flujo de ejecución hasta que la ventana Verificación se cierre
    ventanaVerificacion.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            // Al cerrar la ventana de Verificación, abrir la ventana correspondiente
            if (tipoUsuario.equalsIgnoreCase("ADMINISTRADOR")) {
                new DashboardAdministrador.Inicio().setVisible(true);
            } else if (tipoUsuario.equalsIgnoreCase("MEDICO")) {
                new DashboardMedico.CitasAgendadas().setVisible(true);
            } else if (tipoUsuario.equalsIgnoreCase("RECEPCIONISTA")) {
                new DashboardRecepcionista.AgendarCitas().setVisible(true);
            }
        }
    });

    this.setVisible(false); // Ocultar la ventana de inicio de sesión mientras se verifica
} else {
    JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Por favor, verifica tus datos.", "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
    RegistroUsuario registro = new RegistroUsuario();
    registro.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioDeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioDeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioDeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioDeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioDeSesion().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> combxTipoUsuario;
    private javax.swing.JPasswordField jContraseña;
    private javax.swing.JLabel jLabeFondo;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCorreoEle;
    private javax.swing.JLabel jLabelCrearCuenta;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelMedicalCenter;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelVitalis;
    private javax.swing.JTextField txtFiedlCorreo;
    // End of variables declaration//GEN-END:variables
}
