 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Controlador.UsuarioController;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class RegistroUsuario extends javax.swing.JFrame {
   
    private final UsuarioController usuarioController;
    
    /**
     * Creates new form InicioDeSesion
     */
    public RegistroUsuario() {
        initComponents();
        usuarioController = new UsuarioController();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCodigoAutorizacion = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCURP = new javax.swing.JTextField();
        comboxTipo = new javax.swing.JComboBox<>();
        btnCancelarAdmin = new javax.swing.JButton();
        btnGuardarAdmin = new javax.swing.JButton();
        JCalendarF = new com.toedter.calendar.JDateChooser();
        pwField = new javax.swing.JPasswordField();
        pwFieldConfirmacion = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabelRegis1 = new javax.swing.JLabel();
        jLabelNb8 = new javax.swing.JLabel();
        jLabelNb7 = new javax.swing.JLabel();
        jLabelNb6 = new javax.swing.JLabel();
        jLabelNb5 = new javax.swing.JLabel();
        jLabelNb4 = new javax.swing.JLabel();
        jLabelNb3 = new javax.swing.JLabel();
        jLabelNb2 = new javax.swing.JLabel();
        jLabelNb1 = new javax.swing.JLabel();
        jLabelNb = new javax.swing.JLabel();
        jLabelTVMC = new javax.swing.JLabel();
        jLabelFondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 450, -1));
        getContentPane().add(txtCodigoAutorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 450, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 450, -1));
        getContentPane().add(txtCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 450, -1));

        comboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "MEDICO ", "RECEPCIONISTA" }));
        comboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 170, -1));

        btnCancelarAdmin.setBackground(new java.awt.Color(101, 85, 143));
        btnCancelarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarAdmin.setText("Cancelar");
        btnCancelarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 120, 30));

        btnGuardarAdmin.setBackground(new java.awt.Color(101, 85, 143));
        btnGuardarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAdmin.setText("Guardar");
        btnGuardarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 120, 30));

        JCalendarF.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(JCalendarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 440, -1));
        getContentPane().add(pwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 450, -1));
        getContentPane().add(pwFieldConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 450, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 200, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 643, 130, 20));

        jLabelRegis1.setFont(new java.awt.Font("Arial Black", 0, 26)); // NOI18N
        jLabelRegis1.setText("REGISTRATE");
        getContentPane().add(jLabelRegis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabelNb8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb8.setText("Introduce tu codigo de autorizacion:");
        getContentPane().add(jLabelNb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, 20));

        jLabelNb7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb7.setText("Confirma tu contraseña:");
        getContentPane().add(jLabelNb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, 20));

        jLabelNb6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb6.setText("Contraseña:");
        getContentPane().add(jLabelNb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, 20));

        jLabelNb5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb5.setText("Tipo de cuenta:");
        getContentPane().add(jLabelNb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 20));

        jLabelNb4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb4.setText("Correo electronico:");
        getContentPane().add(jLabelNb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        jLabelNb3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb3.setText("Fecha de nacimiento:");
        getContentPane().add(jLabelNb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        jLabelNb2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb2.setText("CURP:");
        getContentPane().add(jLabelNb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 20));

        jLabelNb1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb1.setText("Apellido:");
        getContentPane().add(jLabelNb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        jLabelNb.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelNb.setText("Nombre (s):");
        getContentPane().add(jLabelNb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabelTVMC.setFont(new java.awt.Font("Arial Black", 0, 23)); // NOI18N
        jLabelTVMC.setText("VITALIS MEDICAL CENTER");
        getContentPane().add(jLabelTVMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        jLabelFondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ISAdmin.png"))); // NOI18N
        getContentPane().add(jLabelFondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAdminActionPerformed
      
    }//GEN-LAST:event_btnCancelarAdminActionPerformed

    private void btnGuardarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAdminActionPerformed

    String nombre = txtNombre.getText();
    String apellido = txtApellido.getText();
    String curp = txtCURP.getText();
    java.util.Date fechaSeleccionada = JCalendarF.getDate();
    if (fechaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Selecciona una fecha válida");
        return;
    }
    java.sql.Date fechaNacimiento = new java.sql.Date(fechaSeleccionada.getTime());
    String correo = txtCorreo.getText();
    String tipoUsuario = (String) comboxTipo.getSelectedItem();
    String contraseña = new String(pwField.getPassword());
    String confirmarContraseña = new String(pwFieldConfirmacion.getPassword());
    String codigoAutorizacion = txtCodigoAutorizacion.getText();

    if (usuarioController.validarCampos(nombre, apellido, curp, fechaNacimiento, correo, tipoUsuario, contraseña, confirmarContraseña, codigoAutorizacion)) {
        if (usuarioController.guardarUsuario(nombre, apellido, curp, fechaNacimiento, correo, tipoUsuario, contraseña, codigoAutorizacion)) {
            JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos(); // Limpia los campos solo si el registro fue exitoso
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el usuario. Por favor, verifica los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btnGuardarAdminActionPerformed

    private void comboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTipoActionPerformed
        
    }//GEN-LAST:event_comboxTipoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        InicioDeSesion inicio = new InicioDeSesion();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void limpiarCampos() {
    txtNombre.setText("");
    txtApellido.setText("");
    txtCURP.setText("");
    JCalendarF.setDate(null);
    txtCorreo.setText("");
    comboxTipo.setSelectedIndex(0); // Seleccionar el primer elemento del combo
    pwField.setText("");
    pwFieldConfirmacion.setText("");
    txtCodigoAutorizacion.setText("");
}


 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JCalendarF;
    private javax.swing.JButton btnCancelarAdmin;
    private javax.swing.JButton btnGuardarAdmin;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboxTipo;
    private javax.swing.JLabel jLabelFondoAdmin;
    private javax.swing.JLabel jLabelNb;
    private javax.swing.JLabel jLabelNb1;
    private javax.swing.JLabel jLabelNb2;
    private javax.swing.JLabel jLabelNb3;
    private javax.swing.JLabel jLabelNb4;
    private javax.swing.JLabel jLabelNb5;
    private javax.swing.JLabel jLabelNb6;
    private javax.swing.JLabel jLabelNb7;
    private javax.swing.JLabel jLabelNb8;
    private javax.swing.JLabel jLabelRegis1;
    private javax.swing.JLabel jLabelTVMC;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JPasswordField pwFieldConfirmacion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtCodigoAutorizacion;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

  


}
