/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashboardAdministrador;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.MedicamentosModel;
import Controlador.MedicamentoControlador;
import Vista.InicioDeSesion;

/**
 *
 * @author rober
 */
public class Medicamentos extends javax.swing.JFrame {

    public Medicamentos() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarMedicamentosEnTabla();    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicamentos = new javax.swing.JTable();
        btnUsuarios = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnMedicamentos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAnadirMedicamento = new javax.swing.JButton();
        btnLimpiarMedicamento = new javax.swing.JButton();
        btnEliminarMedicamento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtUnidades = new javax.swing.JTextField();
        txtTipoVenta = new javax.swing.JTextField();
        btnBuscarMedicamento = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(970, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 170, 30));

        TablaMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Presentacion", "Tipo de venta", "Precio", "Unidades"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMedicamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 480, 660));

        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 170, 30));

        btnPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 170, 30));

        btnCitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCitas.setText("Citas");
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 170, 30));

        btnMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMedicamentos.setText("Medicamentos");
        btnMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 170, 30));

        jPanel2.setBackground(new java.awt.Color(168, 194, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 190, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel8.setText("Unidades:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btnAnadirMedicamento.setText("Añadir");
        btnAnadirMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnadirMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        btnLimpiarMedicamento.setText("Limpiar");
        btnLimpiarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        btnEliminarMedicamento.setText("Eliminar");
        btnEliminarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel7.setText("Presentación:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        txtPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentacionActionPerformed(evt);
            }
        });
        jPanel2.add(txtPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel11.setText("Tipo de venta:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel10.setText("Precio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));
        jPanel2.add(txtUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, -1));
        jPanel2.add(txtTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));
        txtTipoVenta.getAccessibleContext().setAccessibleName("");

        btnBuscarMedicamento.setText("Buscar");
        btnBuscarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 360, 410));

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 810, -1, -1));

        jPanel3.setBackground(new java.awt.Color(143, 158, 138));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INFORMACION DEL MEDICAMENTO");
        jPanel3.add(jLabel9);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 360, 30));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel5.setText("MEDICAMENTOS DISPONIBLES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cuenta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("MEDICAL CENTER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("VITALIS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DashboardMedicamentos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 180, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
        HistorialCitas historialCitas = new HistorialCitas();
        historialCitas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicamentosActionPerformed

    private void txtPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentacionActionPerformed

    private void btnAnadirMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirMedicamentoActionPerformed

        String nombre = txtNombre.getText().trim();
    String presentacion = txtPresentacion.getText().trim();
    String tipoVenta = txtTipoVenta.getText().trim();
    double precio;
    int unidades;

    // Validar campos
    if (nombre.isEmpty() || presentacion.isEmpty() || tipoVenta.isEmpty() || txtPrecio.getText().trim().isEmpty() || txtUnidades.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        return;
    }

    try {
        precio = Double.parseDouble(txtPrecio.getText().trim());
        unidades = Integer.parseInt(txtUnidades.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El precio y las unidades deben ser valores numéricos.");
        return;
    }

    // Insertar medicamento
    MedicamentosModel metodos = new MedicamentosModel();
    if (metodos.insertarMedicamento(nombre, presentacion, tipoVenta, precio, unidades)) {
        JOptionPane.showMessageDialog(this, "Medicamento añadido con éxito.");
        cargarMedicamentosEnTabla(); // Recargar la tabla
        limpiarCampos(); // Limpiar los campos
    } else {
        JOptionPane.showMessageDialog(this, "Error al añadir el medicamento.");
    }
    
    }//GEN-LAST:event_btnAnadirMedicamentoActionPerformed

    private void TablaMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicamentosMouseClicked

    if (evt.getClickCount() == 2) { // Doble clic
        int filaSeleccionada = TablaMedicamentos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un registro.");
            return;
        }

        DefaultTableModel modeloTabla = (DefaultTableModel) TablaMedicamentos.getModel();

        // Asignar valores de la fila seleccionada a los campos
        txtNombre.setText(modeloTabla.getValueAt(filaSeleccionada, 0).toString()); // Índice 0: Nombre
        txtPresentacion.setText(modeloTabla.getValueAt(filaSeleccionada, 1).toString()); // Índice 1: Presentación
        txtTipoVenta.setText(modeloTabla.getValueAt(filaSeleccionada, 2).toString()); // Índice 2: Tipo de Venta
        txtPrecio.setText(modeloTabla.getValueAt(filaSeleccionada, 3).toString()); // Índice 3: Precio
        txtUnidades.setText(modeloTabla.getValueAt(filaSeleccionada, 4).toString()); // Índice 4: Unidades
    }

    }//GEN-LAST:event_TablaMedicamentosMouseClicked

    private void btnEliminarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMedicamentoActionPerformed

        int filaSeleccionada = TablaMedicamentos.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un medicamento para eliminar.");
        return;
    }

    String nombre = TablaMedicamentos.getValueAt(filaSeleccionada, 0).toString();

    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar el medicamento '" + nombre + "'?", "Confirmación", JOptionPane.YES_NO_OPTION);
    if (confirmacion == JOptionPane.YES_OPTION) {
        MedicamentosModel metodos = new MedicamentosModel();
        if (metodos.eliminarMedicamento(nombre)) {
            JOptionPane.showMessageDialog(this, "Medicamento eliminado con éxito.");
            cargarMedicamentosEnTabla(); // Recargar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el medicamento.");
        }
    }
        
    }//GEN-LAST:event_btnEliminarMedicamentoActionPerformed

    private void btnLimpiarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMedicamentoActionPerformed
        // TODO add your handling code here:
   limpiarCampos();
    }//GEN-LAST:event_btnLimpiarMedicamentoActionPerformed

    private void btnBuscarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicamentoActionPerformed
// Obtener los valores ingresados por el usuario
    String nombre = txtNombre.getText().trim();
    String presentacion = txtPresentacion.getText().trim();
    String tipoVenta = txtTipoVenta.getText().trim();

    // Llamar al controlador para buscar medicamentos
    MedicamentoControlador controlador = new MedicamentoControlador();
    List<String[]> medicamentosFiltrados = controlador.buscarMedicamentos(nombre, presentacion, tipoVenta);

    // Actualizar la tabla con los resultados
    DefaultTableModel modeloTabla = (DefaultTableModel) TablaMedicamentos.getModel();
    modeloTabla.setRowCount(0); // Limpiar tabla

    for (String[] medicamento : medicamentosFiltrados) {
        modeloTabla.addRow(medicamento);
    }

    // Mensaje si no hay resultados
    if (medicamentosFiltrados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron medicamentos con los criterios especificados.");
    }
        
    }//GEN-LAST:event_btnBuscarMedicamentoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        // TODO add your handling code here:
        Pacientes paciente = new Pacientes();
        paciente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        cargarMedicamentosEnTabla();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        dispose();
        InicioDeSesion inSes = new InicioDeSesion();
        inSes.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        Inicio usuariosRegistrados = new Inicio();
        usuariosRegistrados.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

private void limpiarCampos() {
    txtNombre.setText("");
    txtPresentacion.setText("");
    txtTipoVenta.setText("");
    txtPrecio.setText("");
    txtUnidades.setText("");
}


private void cargarMedicamentosEnTabla() {
    // Obtener el modelo de la tabla
    DefaultTableModel modeloTabla = (DefaultTableModel) TablaMedicamentos.getModel();

    // Limpiar cualquier dato existente en la tabla
    modeloTabla.setRowCount(0);

    // Crear una instancia del controlador o modelo
    MedicamentosModel metodos = new MedicamentosModel();

    // Llamar al método para cargar los datos
    try {
        metodos.cargarMedicamentosEnTabla(modeloTabla);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los medicamentos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}




    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMedicamentos;
    private javax.swing.JButton btnAnadirMedicamento;
    private javax.swing.JButton btnBuscarMedicamento;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnEliminarMedicamento;
    private javax.swing.JButton btnLimpiarMedicamento;
    private javax.swing.JButton btnMedicamentos;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtTipoVenta;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
}
